### PR TITLE
Add the packaging metadata to build the borg snap

### PR DESCRIPTION
**Pull request by come-maiz**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by come-maiz** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

You can test this snap in an ubuntu 16.04 machine with:

```
$ sudo apt install git snapcraft
$ git clone https://github.com/elopio/borg
$ cd borg
$ git checkout snapcraft
$ snapcraft
$ sudo snap install *.snap --dangerous
```

I tested it and I think it's good enough to publish into the edge channel of the ubuntu store. That will expose it to many new users. The early adopters can help testing it, and then when you are happy, you push it to the stable channel and reach even more users.

If you have any questions or comments, please let me know.

**Comment by crufter** [comment]
This is really interesting. 
Many thanks, for the heads up as well, @elopio

**Comment by come-maiz** [comment]
wow, you are fast :) Thanks for the review @crufter !
Now it would be great if you register the name at https://myapps.developer.ubuntu.com/dev/click-apps/register-name/ and maybe you can push the snap to edge from there, so you see what the store offers.

After that, I can help you setting up travis to push a new revision to the edge channel every time your master branch changes. Then your users on the edge channel will get it automatically updated.

We are here on active development of all the parts, so your feedback will be really appreciated.

**Comment by crufter** [comment]
Will make sure to test drive snapcraft, great job on marketing BTW :P 
Looks like an interesting project.

**Comment by come-maiz** [comment]
Hello @crufter. I'm just coming back from holidays. Did you have a chance to register and push the snap in the store? I'll be available now in case I can help you setting the continuous delivery.

Happy new year! :)

**Comment by popey** [comment]
Hello! Is there anything blocking pushing the borg snap to the store? I'd love to see it in there and start telling my friends how to get borg easily! :)

**Pull request merged**
